/**
Script que lista todos os pedidos em separação, o status do pedido, hora que separação iniciou, finalizou e mais 
informações importantes para o controle da separação dos pedidos.
**/

SELECT
  parr.razaosocial AS RAZAO_SOCIAL,
  TOPP.DESCROPER AS TOP,
  VEN.APELIDO AS VENDEDOR,
  SEP.NUMNOTA,
  SEP.DTSEPARACAO,
  SEP.NUSEPARACAO,
  (
    CASE
      WHEN SEP.NUCONFERENCIA IS NULL THEN 'N'
      ELSE (
        SELECT CON.DESTFINAL
        FROM TGWCON CON
        WHERE CON.NUCONFERENCIA = SEP.NUCONFERENCIA
      )
    END
  ) AS ENVIADO_PARA_DOCA,
  SEP.NUNOTA,
  (
    SELECT CAB1.AD_DHINCLUSAO
    FROM TGFCAB CAB1
    WHERE CAB1.NUNOTA = SEP.NUNOTA
  ) AS DHINCLUSAO_PEDIDO_PEDIDO,
  (
    SELECT CAB2.AD_DTCONFIRMACAO
    FROM TGFCAB CAB2
    WHERE CAB2.NUNOTA = SEP.NUNOTA
  ) AS DTCONFIRMACAO_PEDIDO,
  (
    SELECT CAB3.DTALTER
    FROM TGFCAB CAB3
    WHERE CAB3.NUNOTA = SEP.NUNOTA
  ) AS DTHORAULTALTERACAO_PEDIDO,
  (
    SELECT AD_DHINCLUSAO
    FROM TGFCAB CAB
    WHERE CAB.NUNOTA = (
      SELECT DISTINCT (FVAR.NUNOTA)
      FROM TGFVAR FVAR
      WHERE FVAR.NUNOTAORIG = SEP.NUNOTA
        AND ROWNUM = 1
    )
  ) AS DHINCLUSAO_NOTA,
  (
    SELECT AD_DTCONFIRMACAO
    FROM TGFCAB CAB
    WHERE CAB.NUNOTA = (
      SELECT DISTINCT (FVAR.NUNOTA)
      FROM TGFVAR FVAR
      WHERE FVAR.NUNOTAORIG = SEP.NUNOTA
        AND ROWNUM = 1
    )
  ) AS DHCONFIRMACAO_NOTA,
  (
    SELECT FC_VALOR_OPCAO('TGFCAB', 'AD_TIPOENTREGA', CAB4.AD_TIPOENTREGA)
    FROM TGFCAB CAB4
    WHERE CAB4.NUNOTA = SEP.NUNOTA
  ) AS TIPO_ENTREGA,
  (
    SELECT FC_VALOR_OPCAO('TGWSEP', 'DESCRSITUACAO', VSEP.COD_SITUACAO)
    FROM VGWSITSEP VSEP
    WHERE VSEP.NUSEPARACAO = SEP.NUSEPARACAO
  ) AS SITUACAO_SEPARACAO_WMS,
  SEP.CODDOCA,
  DCA.DESCRICAO AS DESCRICAO_DOCA_WMS,
  SEP.ORDEMCARGA AS O_C,
  (
    SELECT SUM(PRO.PESOBRUTO * ITT.QTDVOLPAD) AS PESOBRUTO
    FROM TGWITT ITT
    INNER JOIN (
      SELECT CODPROD, PESOBRUTO
      FROM TGFPRO
    ) PRO ON (ITT.CODPROD = PRO.CODPROD)
    WHERE SEP.NUTAREFA = ITT.NUTAREFA
  ) AS PESO_BRUTO,
  (
    SELECT SUM(PRO.M3 * ITT.QTDVOLPAD) AS M3
    FROM TGWITT ITT
    INNER JOIN (
      SELECT CODPROD, M3
      FROM TGFPRO
    ) PRO ON (ITT.CODPROD = PRO.CODPROD)
    WHERE SEP.NUTAREFA = ITT.NUTAREFA
  ) AS M3_BRUTO,
  (
    SELECT COUNT(ITT.NUTAREFA) AS QTDTAREFAS
    FROM TGWITT ITT
    WHERE SEP.NUTAREFA = ITT.NUTAREFA
  ) AS QTD_TAREFAS,
  SEP.CODAREACONF AS AREA,
  ARC.NOMEAREACONF AS DESCRICAO_AREA,
  SEP.CODEMPOC AS COD_EMP_OC,
  SEP.CODAREASEP AS COD_AREA_SEP,
  ARS.NOMEAREASEP AS DESCRICAO_AREA_SEP,
  SEP.TRIADO AS TRIAGEM_REALIZADA,
  (
    SELECT MAX(COI.CODUSU) AS CODUSUCONF
    FROM TGWCOI COI
    WHERE SEP.NUCONFERENCIA = COI.NUCONFERENCIA
  ) AS COD_CONFERENTE,
  (
    SELECT MAX(USU.NOMEUSU) AS CODUSUCONF
    FROM TGWCOI COI
    INNER JOIN TSIUSU USU ON COI.CODUSU = USU.CODUSU
    WHERE SEP.NUCONFERENCIA = COI.NUCONFERENCIA
  ) AS USU_CONFERENTE,
  SEP.CODPARC AS COD_PARCEIRO_DESTINO,
  END.ENDERECO AS ENDERECO,
  (
    SELECT parr.nomeparc
    FROM tgwsep sepp
    INNER JOIN tgwsxn sxnn ON sepp.nuseparacao = sxnn.nuseparacao
    INNER JOIN tgfcab cabb ON sxnn.nunota = cabb.nunota
    INNER JOIN tgfpar parr ON cabb.codparc = parr.codparc
    WHERE sepp.nuseparacao = SEP.NUSEPARACAO
      AND ROWNUM <= 1
  ) AS NOME,
  PAR.NOMEPARC AS NOME_PARCEIRO,
  (
    CASE
      WHEN SEP.SITUACAO = 1 THEN '#000000' -- letra preta
      WHEN SEP.SITUACAO = 2 THEN '#FFFFFF' -- letra branca
      WHEN SEP.SITUACAO = 6 THEN '#000000' -- letra preta
      WHEN SEP.SITUACAO = 4 THEN '#000000' -- letra preta
    END
  ) AS FGCOLOR,
  (
    CASE
      WHEN SEP.SITUACAO = 1 THEN '#FFFF00' -- fundo vermelho
      WHEN SEP.SITUACAO = 2 THEN '#0000FF' -- fundo azul
      WHEN SEP.SITUACAO = 6 THEN '#80EE80' -- fundo verde
      WHEN SEP.SITUACAO = 4 THEN '#FFFF00' -- fundo vermelho
    END
  ) AS BKCOLOR,
  CAB.AD_NUMOSDIAG
FROM
  TGWSEP SEP
  INNER JOIN TGWDCA DCA ON DCA.CODDOCA = SEP.CODDOCA
  INNER JOIN TGWSXN SXN ON SXN.NUSEPARACAO = SEP.NUSEPARACAO
  LEFT JOIN TGWARC ARC ON ARC.CODAREACONF = SEP.CODAREACONF
  LEFT JOIN TGWARS ARS ON ARS.CODAREASEP = SEP.CODAREASEP
  INNER JOIN TGWEND END ON END.CODEND = SEP.CODENDDOCA
  LEFT JOIN TGFPAR PAR ON PAR.CODPARC = SEP.CODPARC
  LEFT JOIN TGFCAB CAB ON CAB.NUNOTA = SXN.NUNOTA
  LEFT JOIN TGFVEN VEN ON CAB.CODVEND = VEN.CODVEND
  LEFT JOIN TGFTOP TOP ON TOP.CODTIPOPER = CAB.CODTIPOPER AND TOP.DHALTER = CAB.DHTIPOPER
  INNER JOIN VGWSITSEP VSEP ON VSEP.NUSEPARACAO = SEP.NUSEPARACAO
WHERE
  TRUNC(SEP.DTSEPARACAO) BETWEEN TO_DATE('01/05/2023', 'DD/MM/YYYY') AND TO_DATE('10/07/2023', 'DD/MM/YYYY')
  AND TOP.CODTIPOPER IN :P_TOP
  AND CAB.CODEMP IN :P_CODEMP 
  AND VSEP.COD_SITUACAO IN :SITUACAO 
  AND (SEP.NUSEPARACAO IN :P_NUSEPARACAO OR NVL(:P_NUSEPARACAO, 0) = 0)
  AND (SEP.NUNOTA IN :P_NUNOTA OR NVL(:P_NUNOTA, 0) = 0)
  AND (VEN.CODVEND IN :P_CODVEND OR NVL(:P_CODVEND, 0) = 0)
  AND (CAB.AD_NUMOSDIAG IN :P_AD_NUMOSDIAG OR NVL(:P_AD_NUMOSDIAG, 0) = 0)
