-- Parametros, que deverá vir de um filtro:
-- Dash que mostra toda a movimentação de um produto no wms.
-- :P_CODPROD
-- :P_CODEMP
-- :P_DATAINI AND :P_DATAFIM

SELECT
    CASE
        WHEN (TTR.CODTAREFA = 1 AND EN1.CODEND = EN2.CODEND) THEN 1030
        WHEN (EN1.ENDERECO LIKE '%.9998.%' AND EN2.ENDERECO LIKE '%.9999.001') THEN 1031
        ELSE TTR.CODTAREFA
    END AS CODIGOTAR,
    CASE
        WHEN (TTR.CODTAREFA = 1 AND EN1.CODEND = EN2.CODEND) THEN 'Recontagem'
        WHEN (EN1.ENDERECO LIKE '%.9998.%' AND EN2.ENDERECO LIKE '%.9999.001') THEN 'Corte'
        ELSE TTR.DESCRTAREFA
    END AS TAREFA,
    ITT.IDMAPA,
    ITT.CODPROD AS PRODUTO,
    PRO.DESCRPROD AS DESCRICAO,
    ITT.CODENDORIGEM AS ORIGEM,
    CASE
        WHEN EN1.ENDERECO = EN1.DESCREND THEN EN1.ENDERECO
        ELSE EN1.ENDERECO || ' - ' || EN1.DESCREND
    END AS ENDORI,
    ITT.CODENDDESTINO AS DESTINO,
    CASE
        WHEN EN2.ENDERECO = EN2.DESCREND THEN EN2.ENDERECO
        ELSE EN2.ENDERECO || ' - ' || EN2.DESCREND
    END AS ENDDES,
    ITT.QTDDEST AS QUANTIDADE,
    ITT.CODUSUEXEC AS USUARIO,
    USU.NOMEUSU AS NOME,
    ITT.DHINICIALEXEC AS INICIO,
    ITT.DHFINALEXEC AS FIM,
    CASE
        WHEN ITT.SITUACAO = 'C' THEN 'Cancelado'
        WHEN ITT.SITUACAO = 'F' THEN 'Finalizada'
        ELSE 'Não Esperado'
    END AS STATUS
FROM
    TGWITT ITT
    JOIN TGWEND EN1 ON EN1.CODEND = ITT.CODENDORIGEM
    JOIN TGWEND EN2 ON EN2.CODEND = ITT.CODENDDESTINO
    JOIN TSIUSU USU ON USU.CODUSU = ITT.CODUSUEXEC
    JOIN TGFPRO PRO ON PRO.CODPROD = ITT.CODPROD
    JOIN TGWTAR TAR ON TAR.NUTAREFA = ITT.NUTAREFA
    JOIN TGWTTR TTR ON TTR.CODTAREFA = TAR.CODTAREFA
WHERE
    ITT.CODPROD = :P_CODPROD
    AND ITT.CODEMP = :P_CODEMP
    AND ITT.SITUACAO IN ('C', 'F')
    AND TRUNC(DHINICIALEXEC) BETWEEN :P_DATAINI AND :P_DATAFIM
ORDER BY
    INICIO;
