SELECT ITT.CONTROLE,
	   ITT.NUTAREFA,
	   USU.NOMEUSU AS EXECUTANTE,
	   ITT.DHFINALEXEC AS DT_EXECUCAO,
	   ITT.QTDORIG AS QUANTIDADE,
	   ITT.CODVOLORIG,
	   EDT.DESCREND AS DESCREND_EDT,
	   EOR.DESCREND AS DESCREND_EOR,
	   ITT.CODENDORIGEM AS COD_END_RED_ORIGEM, 
	   EOR.ENDERECO AS ENDERECO_ORIGEM,
	   ITT.CODENDDESTINO AS COD_END_RED_DESTINO,
	   EDT.ENDERECO AS ENDERECO_DESTINO,
	   TAR.CODPARC,
	   PAR.NOMEPARC,
	   NVL((SELECT RUMA.UMA 
			   		FROM TGWRUMA RUMA 
			   	   RIGHT JOIN TGWEPL EPL ON (EPL.IDPALETE = RUMA.IDPALETE) 
			   	   WHERE EPL.CODEMP = ITT.CODEMP
					 AND EPL.CODLOCAL = ITT.CODLOCAL
			   		 AND EPL.CONTROLE = ITT.CONTROLE
					 AND EPL.CODEND = EDT.CODEND
					 AND EPL.CODPROD = PRO.CODPROD 
					 AND EPL.CODVOL = ITT.CODVOLORIG
			   		 AND EPL.CODPARC = TAR.CODPARC),'') AS UMA,
	    PRO.CODPROD AS CODPROD,  PRO.DESCRPROD AS DESCRPROD, 
	   CASE WHEN TTR.DESCRTAREFA  = 'Separação' 
	   			 AND NVL(REC.NURECEBIMENTO, 0) = 0  
				 AND NVL(SEP.NUSEPARACAO, 0) = 0 THEN 'Cancelamento Recebimento'
		    WHEN TTR.DESCRTAREFA  = 'Armazenagem' 
	   			 AND NVL(REC.NURECEBIMENTO, 0) = 0  
				 AND NVL(SEP.NUSEPARACAO, 0) = 0 
				 AND (NOT EXISTS(SELECT 1 FROM TGWRCON RCON WHERE ITT.NUTAREFA = RCON.NUTAREFA) AND TTR.CODTAREFA <> TAR.CODTAREFA) THEN 'Cancelamento Expedição'
			ELSE TTR.DESCRTAREFA END AS TIPOTAREFA,
	   CASE WHEN NVL(REC.NURECEBIMENTO, 0) > 0 THEN '#5FFF7A' 
	   		WHEN NVL(SEP.NUSEPARACAO, 0) > 0 THEN '#FF5F5F' 
	   		ELSE '#FFFFFF' END AS BKCOLOR,
	   CASE WHEN NVL(SEP.NUSEPARACAO, 0) > 0 THEN SEP.NUNOTA
	        WHEN NVL(REC.NURECEBIMENTO, 0) > 0 THEN REC.NUNOTA
			ELSE NULL END AS NUNOTA,
	   CASE WHEN NVL(SEP.NUSEPARACAO, 0) > 0 THEN SEP.NUMNOTA
	        WHEN NVL(REC.NURECEBIMENTO, 0) > 0 THEN (SELECT RCAB.NUMNOTA FROM TGFCAB RCAB WHERE RCAB.NUNOTA = REC.NUNOTA) 
			ELSE NULL END AS NUMNOTA,
	   CASE WHEN NVL(TDT.CODTIPOPER, 0) > 0 THEN TDT.CODTIPOPER
	   		WHEN NVL(TOR.CODTIPOPER, 0) > 0 THEN TOR.CODTIPOPER
			ELSE NULL END AS CODTIPOPER,
	   CASE WHEN NVL(TDT.CODTIPOPER, 0) > 0 THEN TDT.DESCROPER
	   		WHEN NVL(TOR.CODTIPOPER, 0) > 0 THEN TOR.DESCROPER
			ELSE NULL END AS DESCRICAO_TOP,
	   CASE WHEN ITT.TIPTAREFA = 'A' THEN 'Automática' ELSE 'Manual' END AS FORMA_EXECUCAO
FROM TGWITT ITT, TGWTTR TTR, TGWEND EOR, TGWEND EDT, TSIUSU USU, TGFPRO PRO, TGFPAR PAR, TGWTAR TAR    , TGWREC REC, TGWSEP SEP, TGFCAB COR, TGFCAB CDT, TGFTOP TOR, TGFTOP TDT   
 

WHERE TAR.NUTAREFA = ITT.NUTAREFA

	AND REC.NUTAREFA(+) = TAR.NUTAREFA
	AND SEP.NUTAREFA(+) = TAR.NUTAREFA
	AND COR.NUNOTA(+) = REC.NUNOTA
	AND CDT.NUNOTA(+) = SEP.NUNOTA
	AND TOR.CODTIPOPER(+) = COR.CODTIPOPER 
	AND TOR.DHALTER(+) = COR.DHTIPOPER 
	AND TDT.CODTIPOPER(+) = CDT.CODTIPOPER
	AND TDT.DHALTER(+) = CDT.DHTIPOPER   
		 

	AND TTR.CODTAREFA = TAR.CODTAREFA
	AND EOR.CODEND = ITT.CODENDORIGEM  
	AND EDT.CODEND = ITT.CODENDDESTINO
	AND USU.CODUSU = ITT.CODUSUEXEC
	AND PRO.CODPROD = ITT.CODPROD
	AND ITT.SITUACAO = 'F'
	AND PAR.CODPARC = TAR.CODPARC
    AND (ITT.CODENDORIGEM = :CODENDORIGEM
        OR ITT.CODENDDESTINO = :CODENDDESTINO)  
    AND TRUNC(ITT.DHFINALEXEC) >= TO_DATE(:DHINICIAL,'DD/MM/YYYY HH:MM:')  
    AND TRUNC(ITT.DHFINALEXEC) <= SYSDATE 

ORDER BY ITT.DHFINALEXEC