SELECT 

    FITE.NUNOTA,
    FITE.SEQUENCIA,
    FITE.CODEMP,
    FITE.CODPROD,
    PROD.DESCRPROD,
    PROD.DESCRPRODNFE,
    PROD.AD_UTILIZAVLM,
    CASE PROD.UTILIZAWMS
        WHEN 'S' THEN 1
        WHEN 'N' THEN 0
        ELSE NULL
    END AS UTILIZAWMS,
    PROD.USASERIEFAB,
    PROD.USASERIESEPWMS,
    PROD.FABRICANTE,
    FITE.USOPROD,
    FITE.ORIGPROD,
    FITE.SOLCOMPRA,
    FITE.PENDENTE,
    FITE.QTDNEG,
    FITE.CODVOL,
    FITE.ALTURA,
    PROD.ALTURA AS ALTURA_PRODUTO,
    FITE.LARGURA,
    PROD.LARGURA AS LARGURA_PRODUTO,
    FITE.M3,
    FITE.ESPESSURA,
    FITE.RESERVA,
    FITE.QTDWMS,
    FITE.PRODUTONFE,
    FITE.AD_QTDPROGRAMADA,
    FITE.AD_NCM

FROM TGFITE FITE
INNER JOIN TGFPRO PROD ON FITE.CODPROD = PROD.CODPROD
WHERE FITE.NUNOTA = 4671346
