WITH EstoqueCTE AS (
    SELECT 
        CODEMP, 
        CODPROD, 
        SUM(NVL(ESTOQUE, 0)) AS ESTOQUE
    FROM 
        TGFEST
    WHERE 
        CODLOCAL = 930000000
    GROUP BY 
        CODEMP, CODPROD
),

EstoqueWmsCTE AS (
    SELECT
       CODEMP,
       CODPROD,
       SUM(NVL(ESTOQUE, 0)) AS ESTOQUEWMS
    FROM 
        TGWEST
    WHERE
        CODEMP = 11
    GROUP BY
        CODEMP, CODPROD
),

-- CTE para calcular o TOTAL_QTD_EM_UMA por NUNOTA e CODPROD
TotalUMA_CTE AS (
    SELECT 
        REC.NUNOTA,
        ITE.CODPROD,
        SUM(RCON.QTDRECEBIDAVOLPAD) AS TOTAL_QTD_EM_UMA
    FROM 
        TGWREC REC
    INNER JOIN TGFITE ITE ON ITE.NUNOTA = REC.NUNOTA AND ITE.SEQUENCIA > 0
    LEFT JOIN TGWRCON RCON ON RCON.NURECEBIMENTO = REC.NURECEBIMENTO AND RCON.CODPROD = ITE.CODPROD
    WHERE 
        REC.NUNOTA = :NUNOTA
    GROUP BY 
        REC.NUNOTA,
        ITE.CODPROD
)

SELECT 
    
    REC.NUNOTA,
    RCON.UMA,
    REC.NURECEBIMENTO,
    REC.NUCONFERENCIA,
    ITE.CODPROD,
    RCON.CODBARRA,
    PROD.DESCRPROD,
    ITE.QTDNEG,
    ITE.QTDWMS,
    ITE.SEQUENCIA,
    COI.QTDECONF,
    COI.QTDEDIF,
    NVL(TotalUMA_CTE.TOTAL_QTD_EM_UMA, 0) AS TOTAL_QTD_EM_UMA,
    NVL(SUM(EstoqueCTE.ESTOQUE), 0) AS ESTOQUE,
    NVL(SUM(EstoqueWmsCTE.ESTOQUEWMS), 0) AS ESTOQUEWMS,
    -- Calculando a diferença entre QTDNEG e TOTAL_QTD_EM_UMA
    ITE.QTDNEG - NVL(TotalUMA_CTE.TOTAL_QTD_EM_UMA, 0) AS DIFERENCA_QTD,
    RCON.NUTAREFA,
    RCON.DHINI,
    RCON.CODUSUCONF,
    USU.NOMEUSU,
    ITT.CODENDDESTINO AS CODENDORIGEM,
    ITT.CODENDDESTINO,
    CASE
     WHEN ( ITE.QTDNEG - NVL(TotalUMA_CTE.TOTAL_QTD_EM_UMA, 0) = 0 )  THEN 'darkblue'
     ELSE 'darkred'
    END AS FGCOLOR	
    
FROM 

    TGWREC REC
    
INNER JOIN TGFITE ITE  ON ITE.NUNOTA = REC.NUNOTA AND ITE.SEQUENCIA > 0
LEFT JOIN  TGWCOI COI  ON COI.NUCONFERENCIA = REC.NUCONFERENCIA AND COI.CODPROD = ITE.CODPROD
LEFT JOIN  TGWRCON RCON ON RCON.NURECEBIMENTO = REC.NURECEBIMENTO AND RCON.CODPROD = ITE.CODPROD
INNER JOIN TGFPRO PROD ON PROD.CODPROD = ITE.CODPROD
LEFT JOIN EstoqueCTE ON EstoqueCTE.CODPROD = PROD.CODPROD AND EstoqueCTE.CODEMP = ITE.CODEMP
LEFT JOIN EstoqueWmsCTE ON EstoqueWmsCTE.CODPROD = PROD.CODPROD AND EstoqueWmsCTE.CODEMP = ITE.CODEMP
LEFT JOIN TotalUMA_CTE ON TotalUMA_CTE.NUNOTA = REC.NUNOTA AND TotalUMA_CTE.CODPROD = ITE.CODPROD
LEFT JOIN TGWTAR TAR ON TAR.NUTAREFA = RCON.NUTAREFA
LEFT JOIN TGWITT ITT ON TAR.NUTAREFA = ITT.NUTAREFA AND ITT.CODPROD = ITE.CODPROD
LEFT JOIN TSIUSU USU ON USU.CODUSU = RCON.CODUSUCONF

WHERE
 
    REC.NUNOTA =  :NUNOTA
    
GROUP BY 

    REC.NUNOTA,
    RCON.UMA,
    REC.NURECEBIMENTO,
    REC.NUCONFERENCIA,
    ITE.CODPROD,
    RCON.CODBARRA,
    PROD.DESCRPROD,
    ITE.QTDNEG,
    ITE.QTDWMS,
    ITE.SEQUENCIA,
    COI.QTDECONF,
    COI.QTDEDIF,
    TotalUMA_CTE.TOTAL_QTD_EM_UMA,
    RCON.NUTAREFA,
    RCON.DHINI,
    RCON.CODUSUCONF,
    USU.NOMEUSU,
    ITT.CODENDDESTINO
    
ORDER BY ITE.SEQUENCIA, ITE.CODPROD, RCON.UMA