/*
 @author: Danilo Fernando <danilo.fernando@grupocopar.com.br>
 @date 29/01/2024
 
 Simples consulta usada no DASH 1581.
 Retorna alguns dados dos parceiros que são clientes .
 Mostra o limite liberado para o cliente e quanto ele ainda tem de limite disponível.
 
*/
SELECT 

    T.CODPARC AS CODPARC,
    T.NOMEPARC AS PARCEIRO,
    T.RAZAOSOCIAL,
    T.NOMEEND AS ENDERECO,
    T.NUMEND AS NR,
    T.COMPLEMENTO,
    T.NOMEBAI AS BAIRRO,
    T.NOMECID AS CIDADE,
    T.DESCRICAO AS UF,
    T.TELEFONE,
    T.EMAIL,
    T.EMAILNFE,
    T.DTULTNEGOC AS ULTIMACOMPRA,
    T.CGC_CPF AS CNPJ,
    FC_VALOR_OPCAO('TGFPAR', 'SITUACAO', T.SITUACAO) AS SITUACAO,
    FC_VALOR_OPCAO('TGFPAR', 'BLOQUEAR', T.BLOQUEAR) AS BLOQUEAR,
    T.MOTBLOQ AS MOTIVOBLOQUEIO,
    T.LIMCRED AS LIMITECREDITO,
    T.LIMITEDISPONIVEL

FROM ( SELECT 
    PARCEIRO.CODPARC,
    PARCEIRO.NOMEPARC,
    PARCEIRO.RAZAOSOCIAL,
    ENDERECO.NOMEEND,
    PARCEIRO.NUMEND,
    PARCEIRO.COMPLEMENTO,
    BAIRRO.NOMEBAI,
    CIDADE.NOMECID,
    UFS.DESCRICAO,
    PARCEIRO.TELEFONE,
    PARCEIRO.AD_FONE2,
    PARCEIRO.AD_FONE3,
    PARCEIRO.AD_FONE4,
    PARCEIRO.EMAIL,
    PARCEIRO.EMAILNFE,
    PARCEIRO.DTULTNEGOC,
    PARCEIRO.CGC_CPF,
    PARCEIRO.SITUACAO,
    PARCEIRO.OBSERVACOES,
    PARCEIRO.BLOQUEAR,
    PARCEIRO.MOTBLOQ,
    PARCEIRO.LIMCRED,
    (FC_CALLIMCRED_DCCO(PARCEIRO.CODPARC)) AS LIMITEDISPONIVEL,
    PARCEIRO.LIMCREDMENSAL
    
    
FROM TGFPAR PARCEIRO 

INNER JOIN TSIBAI BAIRRO ON PARCEIRO.CODBAI = BAIRRO.CODBAI
INNER JOIN TSICID CIDADE ON PARCEIRO.CODCID = CIDADE.CODCID
INNER JOIN TSIEND ENDERECO ON PARCEIRO.CODEND = ENDERECO.CODEND
INNER JOIN TSIUFS UFS ON CIDADE.UF = UFS.CODUF


WHERE PARCEIRO.CLIENTE = 'S'
AND PARCEIRO.ATIVO = 'S'
-- Adicionando as opções ao WHERE, se fornecidas
        AND (:PARCEIRO IS NULL OR PARCEIRO.CODPARC = :PARCEIRO)
        AND (:CIDADE IS NULL OR CIDADE.CODCID = :CIDADE)
        AND (:BAIRRO IS NULL OR BAIRRO.CODBAI = :BAIRRO)
        AND (:UF IS NULL OR UFS.CODUF = :UF)
        AND (PARCEIRO.BLOQUEAR <> :BLOQUEADO)

ORDER BY PARCEIRO.NOMEPARC, PARCEIRO.LIMCRED
) T
WHERE T.LIMITEDISPONIVEL > 0 AND T.LIMCRED > 0

/