SELECT
    WIVR.CODEMP,
    VWD.NUIVT,
    IVT.DTINICIO,
        MAX(WIVR.AD_CONTAGEM) || 'º Contagem' AS CONTAGEM,
    VWD.CODEND,
    VWD.CODPROD,
    PROD.REFERENCIA,
    PROD.DESCRPROD,
    VWD.ESTOQUE AS QUANTIDADE,
    VWD.QTD_CONTAGEM_ATIVA AS QTDFINAL,
    (VWD.QTD_CONTAGEM_ATIVA - VWD.ESTOQUE) AS DIVERGENCIA,
    
    OBTEMCUSTO2(VWD.CODPROD, WIVR.CODEMP, TRUNC(IVT.DTINICIO), 3) AS CUS_UNI_SEMICM,
    
    CASE
        WHEN (VWD.ESTOQUE < VWD.QTD_CONTAGEM_ATIVA) THEN (ABS(VWD.ESTOQUE - VWD.QTD_CONTAGEM_ATIVA) * NVL(OBTEMCUSTO2(VWD.CODPROD, WIVR.CODEMP, TRUNC(IVT.DTINICIO), 3),0))
        ELSE 0
    END AS CUSTOPOS,
    
    CASE
        WHEN (VWD.ESTOQUE > VWD.QTD_CONTAGEM_ATIVA) THEN (ABS(VWD.ESTOQUE - VWD.QTD_CONTAGEM_ATIVA) * NVL(OBTEMCUSTO2(VWD.CODPROD, WIVR.CODEMP, TRUNC(IVT.DTINICIO), 3),0))
        ELSE 0
    END AS CUSTONEG,
    
    CASE
        WHEN (VWD.ESTOQUE <> VWD.QTD_CONTAGEM_ATIVA) THEN (ABS(VWD.ESTOQUE - VWD.QTD_CONTAGEM_ATIVA) * NVL(OBTEMCUSTO2(VWD.CODPROD, WIVR.CODEMP, TRUNC(IVT.DTINICIO), 3),0))
        ELSE 0
    END AS CUSTOTAL,
    
    ( VWD.QTD_CONTAGEM_ATIVA * NVL(OBTEMCUSTO2(VWD.CODPROD, WIVR.CODEMP, TRUNC(IVT.DTINICIO), 3),0))AS CUSTOGERAL
    
FROM SANKHYA.VW_WMSINVT_CONFERENCIA_DCCO VWD
LEFT JOIN TGWIVR WIVR ON VWD.NUIVT = WIVR.NUIVT
                    AND VWD.CODPROD = WIVR.CODPROD
                    AND VWD.CODEND = WIVR.CODEND

INNER JOIN TGFPRO PROD ON PROD.CODPROD = WIVR.CODPROD
INNER JOIN TGWIVT IVT ON IVT.NUIVT = VWD.NUIVT


WHERE VWD.NUIVT = :INVENTARIO 
      AND (VWD.CONFERENCIA_1 <> 'OK' OR VWD.CONFERENCIA_1 IS NULL)
      AND (VWD.CONFERENCIA_2 <> 'OK' OR VWD.CONFERENCIA_2 IS NULL )
      AND (VWD.CONFERENCIA_3 <> 'OK' OR VWD.CONFERENCIA_3 IS NULL )
      AND (VWD.CONFERENCIA_4 <> 'OK' OR VWD.CONFERENCIA_4 IS NULL )
      AND (VWD.CONFERENCIA_5 <> 'OK' OR VWD.CONFERENCIA_5 IS NULL )
    
GROUP BY WIVR.CODEMP, WIVR.CODPROD, IVT.DTINICIO, VWD.NUIVT, VWD.CODPROD, 
        PROD.REFERENCIA, PROD.DESCRPROD, VWD.ESTOQUE, VWD.CODEND, VWD.QTD_CONTAGEM_ATIVA, VWD.ESTOQUE

/
OBTEMCUSTO2(TGWIVR.CODPROD, TGWIVR.CODEMP, TRUNC(TGWIVR.DHCONTAGEM), 3) AS CUS_UNI_SEMICM
/
CASE WHEN I.FINALIZADA = 'S' AND I.QTDCONSID < I.QTDEST THEN
/*FC_PRECOPROD_DCCO(I.DTCONTAGEM,I.CODPROD,I.CODEMP,1)*/NVL(I.CUSSEMICMS,0)*(I.QTDCONSID - I.QTDEST)
ELSE
0
END) AS CNEGA