   /*
   Objetivo: SEQUENCIA DE PREENCHIMENTO DAS TABELAS PELO WMS QUANDO DO RECEBIMENTO
   
   */

/* PROCESSO COMPLETO DE RECEBIMENTO DENTRO DO BANCO */

SELECT * FROM TGWREC WHERE NURECEBIMENTO = 3721 --05/10/2023
/
SELECT * FROM TGWCON WHERE NUCONFERENCIA = 25298
/
SELECT * FROM TGWCOI WHERE NUCONFERENCIA = 25263
/
SELECT * FROM TGWTAR WHERE NUTAREFA = 28971
/
SELECT * FROM TGWITT WHERE NUTAREFA = 28971
/
/* Outras consultas relevantes*/
SELECT * FROM TGWRXN WHERE NUNOTA = 4178698 --Notas por recebimento.
/
SELECT * FROM TGWITER WHERE NURECEBIMENTO = 3719 -- Itens da nota do recebimento
/
SELECT * FROM VGWREC WHERE NURECEBIMENTO = 3719 -- VIEW DE RECEBIMENTO __ RECEBIMENTO DE MERCADORIA
/
SELECT * FROM TSIUSU WHERE CODUSU = 669 -- 
/

/* ******************** EDIT DAS CONSULTAS *********************************************************/
EDIT TGWREC WHERE NURECEBIMENTO = 3719 --
/
EDIT TGWCON WHERE NUCONFERENCIA = 25263
/
EDIT TGWCOI WHERE NUCONFERENCIA = 25263
/
EDIT TGWTAR WHERE NUTAREFA = 28971
/
EDIT TGWITT WHERE NUTAREFA = 34856
/



/
EDIT TSIUSU WHERE CODUSU = 1083 -- ANTONIOO

/
SELECT * FROM TGFCON
/
SELECT * FROM TGWRCON
/
SELECT * FROM TGFCCO
/
SELECT * FROM TGWICC
/
