DROP VIEW SANKHYA.VW_WMSIVTCONTAGEM_DCCO;

CREATE OR REPLACE FORCE VIEW SANKHYA.VW_WMSINVTCONTAGEM_DCCO

BEQUEATH DEFINER
AS 

SELECT 
    
    W.NUIVT,
    W.CODEMP,
    W.CODLOCAL,
    W.CODEND,
    W.CODPROD,
    W.REFERENCIA,
    
    W.ESTOQUE_COMERCIAL, 
    
    W.QTDESTLOGICA,
    W.CONTAGEM_VLM,
    W.QTD_CONTAGEM_ATIVA,
    W.NR_CONTAGEM_ATIVA,
    W.APURACAO_FINAL,
    CASE
        WHEN W.APURACAO_FINAL = 0 THEN 'Correto'
        WHEN W.APURACAO_FINAL < 0 THEN 'Negativo'
        WHEN W.APURACAO_FINAL > 0 THEN 'Positivo'
    END AS STATUS,
    
    
    W.PRECO,
    (W.APURACAO_FINAL * W.PRECO) AS CUSTO_TOTAL,
    W.CONTAGEM_1,
    W.CONTAGEM_2,
    W.CONTAGEM_3,
    W.CONTAGEM_4,
    W.CONTAGEM_5,
    W.CONTAGEM_6,
    W.CONTAGEM_7,
    W.CONTAGEM_8,
    W.CONTAGEM_9,
    W.CONTAGEM_10,
    
    W.SOMATORIO_CONTAGEM_GERAL

FROM
(SELECT
 
    VW.NUIVT,
    VW.CODEMP,
    VW.CODLOCAL,
    VW.CODEND,
    VW.CODPROD,
    VW.REFERENCIA,
    
    VW.ESTOQUE_COMERCIAL, 
    
    VW.QTDESTLOGICA,
    NVL(VW.CONTAGEM_VLM,0) AS CONTAGEM_VLM,
    VW.QTD_CONTAGEM_ATIVA,
    VW.NR_CONTAGEM_ATIVA,
    
    (NVL(VW.QTD_CONTAGEM_ATIVA,0) + NVL(VW.CONTAGEM_VLM,0)) AS SOMATORIO_CONTAGEM_GERAL,
    ((NVL(VW.QTD_CONTAGEM_ATIVA,0) + NVL(VW.CONTAGEM_VLM,0)) - VW.ESTOQUE_COMERCIAL) AS APURACAO_FINAL,
    
    VW.PRECO,
    
    VW.CONTAGEM_1,
    VW.CONTAGEM_2,
    VW.CONTAGEM_3,
    VW.CONTAGEM_4,
    VW.CONTAGEM_5,
    VW.CONTAGEM_6,
    VW.CONTAGEM_7,
    VW.CONTAGEM_8,
    VW.CONTAGEM_9,
    VW.CONTAGEM_10

FROM VW_WMSINVENTARIO_DCCO VW 
--WHERE VW.NUIVT = 152

) W