DROP VIEW SANKHYA.VW_WMSINVENTARIO_DCCO;

CREATE OR REPLACE FORCE VIEW SANKHYA.VW_WMSINVENTARIO_DCCO

BEQUEATH DEFINER
AS 

SELECT 
    *
FROM (
    SELECT
    IVR.NUIVT,
    IVR.CODEMP,
    IVR.CODLOCAL,
    IVR.CODEND,
    IVR.CODPROD,
    PROD.REFERENCIA,
    IVR.QTDESTLOGICA,
    IVR.QTDESTCONTADA,
    IVR.AD_CONTAGEM,
    (SELECT IVLM.QTDESTCONTADA FROM TGWIVR IVLM WHERE IVLM.CODEMP = IVR.CODEMP AND IVLM.CODEND = 15200
     AND IVLM.CODPROD = IVR.CODPROD AND IVLM.NUIVT = IVR.NUIVT AND IVR.ATIVA = 'S' ) AS CONTAGEM_VLM,
     
    (SELECT SUM(ESTOQUECOMERCIAL.ESTOQUE) FROM TGFEST ESTOQUECOMERCIAL 
        WHERE ESTOQUECOMERCIAL.CODEMP = IVR.CODEMP AND ESTOQUECOMERCIAL.CODPROD = IVR.CODPROD 
        AND ESTOQUECOMERCIAL.CODLOCAL NOT IN ('990000000')) AS ESTOQUE_COMERCIAL, 
        
    (SELECT ICA.QTDESTCONTADA FROM TGWIVR ICA WHERE ICA.CODEMP = IVR.CODEMP AND ICA.CODPROD = IVR.CODPROD
    AND ICA.NUIVT = IVR.NUIVT AND ICA.ATIVA = 'S' AND ICA.CODEND = IVR.CODEND) AS QTD_CONTAGEM_ATIVA,    
    
    (SELECT ICA.AD_CONTAGEM FROM TGWIVR ICA WHERE ICA.CODEMP = IVR.CODEMP AND ICA.CODPROD = IVR.CODPROD
    AND ICA.NUIVT = IVR.NUIVT AND ICA.ATIVA = 'S' AND ICA.CODEND = IVR.CODEND) AS NR_CONTAGEM_ATIVA,
        
     
    CUSTO.ENTRADACOMICMS AS PRECO
    
  FROM TGWIVR IVR
  INNER JOIN TGFPRO PROD ON PROD.CODPROD = IVR.CODPROD
  INNER JOIN TGFCUS CUSTO ON CUSTO.CODEMP = IVR.CODEMP AND CUSTO.CODPROD = IVR.CODPROD
) T

PIVOT (
  SUM(QTDESTCONTADA) FOR AD_CONTAGEM IN (1 AS CONTAGEM_1, 2 AS CONTAGEM_2, 3 AS CONTAGEM_3, 4 AS CONTAGEM_4, 5 AS CONTAGEM_5, 
                                         6 AS CONTAGEM_6, 7 AS CONTAGEM_7, 8 AS CONTAGEM_8, 9 AS CONTAGEM_9, 10 AS CONTAGEM_10)
);