/*
* View: VW_WMSINVENTARIO3_DCCO
* Descrição: View para gestão de inventário com múltiplas contagens
* Última atualização: 2024
*/

DROP VIEW SANKHYA.VW_WMSINVENTARIO3_DCCO;

CREATE OR REPLACE FORCE VIEW SANKHYA.VW_WMSINVENTARIO3_DCCO (
    NUIVT, CODEMP, CODLOCAL, CODEND, CODPROD,
    REFERENCIA, QTDESTLOGICA, CONTAGEM_VLM, SOMA_CONTAGEM_PICKING, ESTOQUE_COMERCIAL,
    QTD_CONTAGEM_ATIVA, NR_CONTAGEM_ATIVA, ESTOQUECTE,
    END_RUA, END_PREDIO, END_RUA_PREDIO,
    CONTAGEM_1, CONTAGEM_2,
    CONTAGEM_3, CONTAGEM_4, CONTAGEM_5, CONTAGEM_6, CONTAGEM_7,
    CONTAGEM_8, CONTAGEM_9, CONTAGEM_10
) BEQUEATH DEFINER AS
SELECT
    "NUIVT", "CODEMP", "CODLOCAL", "CODEND", "CODPROD", "REFERENCIA", "QTDESTLOGICA", 
    "CONTAGEM_VLM", "SOMA_CONTAGEM_PICKING", "ESTOQUE_COMERCIAL", "QTD_CONTAGEM_ATIVA", 
    "NR_CONTAGEM_ATIVA", "ESTOQUECTE", "END_RUA", "END_PREDIO", "END_RUA_PREDIO",
    MAX(CASE WHEN AD_CONTAGEM = 1 THEN QTDESTCONTADA ELSE NULL END) AS CONTAGEM_1,
    MAX(CASE WHEN AD_CONTAGEM = 2 THEN QTDESTCONTADA ELSE NULL END) AS CONTAGEM_2,
    MAX(CASE WHEN AD_CONTAGEM = 3 THEN QTDESTCONTADA ELSE NULL END) AS CONTAGEM_3,
    MAX(CASE WHEN AD_CONTAGEM = 4 THEN QTDESTCONTADA ELSE NULL END) AS CONTAGEM_4,
    MAX(CASE WHEN AD_CONTAGEM = 5 THEN QTDESTCONTADA ELSE NULL END) AS CONTAGEM_5,
    MAX(CASE WHEN AD_CONTAGEM = 6 THEN QTDESTCONTADA ELSE NULL END) AS CONTAGEM_6,
    MAX(CASE WHEN AD_CONTAGEM = 7 THEN QTDESTCONTADA ELSE NULL END) AS CONTAGEM_7,
    MAX(CASE WHEN AD_CONTAGEM = 8 THEN QTDESTCONTADA ELSE NULL END) AS CONTAGEM_8,
    MAX(CASE WHEN AD_CONTAGEM = 9 THEN QTDESTCONTADA ELSE NULL END) AS CONTAGEM_9,
    MAX(CASE WHEN AD_CONTAGEM = 10 THEN QTDESTCONTADA ELSE NULL END) AS CONTAGEM_10
FROM (
    SELECT
        IVR.NUIVT,
        IVR.CODEMP,
        IVR.CODLOCAL,
        IVR.CODEND,
        IVR.CODPROD,
        PROD.REFERENCIA,
        IVR.QTDESTLOGICA,
        IVR.QTDESTCONTADA,
        IVR.AD_CONTAGEM,
        
        (SELECT IVLM.QTDESTCONTADA 
         FROM TGWIVR IVLM 
         WHERE IVLM.CODEMP = IVR.CODEMP 
         AND IVLM.CODEND = 15200
         AND IVLM.CODPROD = IVR.CODPROD 
         AND IVLM.NUIVT = IVR.NUIVT 
         AND (IVLM.ATIVA = 'S' OR IVLM.AD_BKP_ATIVA = 'S')) AS CONTAGEM_VLM,
        
        (SELECT SUM(IVLM.QTDESTCONTADA) 
         FROM TGWIVR IVLM 
         WHERE IVLM.CODEMP = IVR.CODEMP 
         AND IVLM.CODEND <> 15200
         AND IVLM.CODPROD = IVR.CODPROD 
         AND IVLM.NUIVT = IVR.NUIVT 
         AND (IVLM.ATIVA = 'S' OR IVLM.AD_BKP_ATIVA = 'S')) AS SOMA_CONTAGEM_PICKING,
        
        (SELECT SUM(ESTOQUECOMERCIAL.ESTOQUE) 
         FROM TGFEST ESTOQUECOMERCIAL
         WHERE ESTOQUECOMERCIAL.CODEMP = IVR.CODEMP 
         AND ESTOQUECOMERCIAL.CODPROD = IVR.CODPROD 
         AND ESTOQUECOMERCIAL.CODLOCAL NOT IN ('990000000')) AS ESTOQUE_COMERCIAL,
        
        (SELECT ICA.QTDESTCONTADA 
         FROM TGWIVR ICA 
         WHERE ICA.CODEMP = IVR.CODEMP 
         AND ICA.CODPROD = IVR.CODPROD
         AND ICA.NUIVT = IVR.NUIVT 
         AND (ICA.ATIVA = 'S' OR ICA.AD_BKP_ATIVA = 'S') 
         AND ICA.CODEND = IVR.CODEND) AS QTD_CONTAGEM_ATIVA,
        
        (SELECT ICA.AD_CONTAGEM 
         FROM TGWIVR ICA 
         WHERE ICA.CODEMP = IVR.CODEMP 
         AND ICA.CODPROD = IVR.CODPROD
         AND ICA.NUIVT = IVR.NUIVT 
         AND (ICA.ATIVA = 'S' OR ICA.AD_BKP_ATIVA = 'S') 
         AND ICA.CODEND = IVR.CODEND) AS NR_CONTAGEM_ATIVA,

        (SELECT CTE.QTDEST 
         FROM TGFCTE CTE 
         WHERE CTE.CODEMP = IVR.CODEMP 
         AND CTE.CODPROD = IVR.CODPROD 
         AND CTE.CODLOCAL = '930000000' 
         AND TRUNC(CTE.DTCONTAGEM) = TRUNC(IVT.DTINICIO) 
         FETCH FIRST 1 ROW ONLY) AS ESTOQUECTE,

        SUBSTR(ENDERECO.ENDERECO, 4, 2) AS END_RUA,
        SUBSTR(ENDERECO.ENDERECO, 7, 3) AS END_PREDIO,
        SUBSTR(ENDERECO.ENDERECO, 4, 2) || '.' || SUBSTR(ENDERECO.ENDERECO, 7, 3) AS END_RUA_PREDIO
        
    FROM TGWIVR IVR
    INNER JOIN TGFPRO PROD ON PROD.CODPROD = IVR.CODPROD
    INNER JOIN TGFCUS CUSTO ON CUSTO.CODEMP = IVR.CODEMP AND CUSTO.CODPROD = IVR.CODPROD
    INNER JOIN TGWIVT IVT ON IVT.NUIVT = IVR.NUIVT
    INNER JOIN TGWEND ENDERECO ON ENDERECO.CODEND = IVR.CODEND
) T
GROUP BY
    "NUIVT", "CODEMP", "CODLOCAL", "CODEND", "CODPROD", "REFERENCIA", "QTDESTLOGICA",
    "CONTAGEM_VLM", "SOMA_CONTAGEM_PICKING", "ESTOQUE_COMERCIAL", "QTD_CONTAGEM_ATIVA",
    "NR_CONTAGEM_ATIVA", "ESTOQUECTE", "END_RUA", "END_PREDIO", "END_RUA_PREDIO";