DROP VIEW SANKHYA.VW_WMSINVT_CONFERENCIA_DCCO;

CREATE OR REPLACE FORCE VIEW SANKHYA.VW_WMSINVT_CONFERENCIA_DCCO
(NUIVT, CODEMP, CODPROD, CODEND, REFERENCIA, 
 DESCPROD, ESTOQUE, CONTAGEM_1, CONFERENCIA_1, CONTAGEM_2, 
 CONFERENCIA_2, CONTAGEM_3, CONFERENCIA_3, CONTAGEM_4, CONFERENCIA_4, 
 CONTAGEM_5, CONFERENCIA_5, QTD_CONTAGEM_ATIVA, NR_CONTAGEM_ATIVA, ESTOQUE_COMERCIAL, 
 ESTOQUECTE, DIVERGENCIA, APURACAO_FINAL, STATUS)
BEQUEATH DEFINER
AS 
SELECT 
    VW.NUIVT,
    VW.CODEMP,
    VW.CODPROD,
    VW.CODEND,
    VW.REFERENCIA,
    VW.CODPROD || ' - ' || PROD.DESCRPROD AS DESCPROD,
    VW.QTDESTLOGICA AS ESTOQUE,
    
    VW.CONTAGEM_1,
    CASE
        WHEN VW.CONTAGEM_1 IS NULL THEN NULL
        WHEN VW.CONTAGEM_1 = VW.QTDESTLOGICA THEN 'OK'
        ELSE 'Erro'
    END AS "CONFERENCIA_1",
    VW.CONTAGEM_2,
    CASE
        WHEN VW.CONTAGEM_2 IS NULL THEN NULL 
        WHEN VW.CONTAGEM_2 = VW.QTDESTLOGICA 
             OR VW.CONTAGEM_2 = VW.CONTAGEM_1 THEN 'OK'
        ELSE 'Erro'
    END AS "CONFERENCIA_2",
    VW.CONTAGEM_3,
    CASE
        WHEN VW.CONTAGEM_3 IS NULL THEN NULL 
        WHEN VW.CONTAGEM_3 = VW.QTDESTLOGICA 
             OR VW.CONTAGEM_3 = VW.CONTAGEM_1 OR VW.CONTAGEM_3 = VW.CONTAGEM_2 THEN 'OK'
        ELSE 'Erro'
    END AS "CONFERENCIA_3",
    VW.CONTAGEM_4,
    CASE
        WHEN VW.CONTAGEM_4 IS NULL THEN NULL 
        WHEN VW.CONTAGEM_4 = VW.QTDESTLOGICA 
             OR VW.CONTAGEM_4 = VW.CONTAGEM_1
                OR VW.CONTAGEM_4 = VW.CONTAGEM_2 
                    OR VW.CONTAGEM_4 = VW.CONTAGEM_3 THEN 'OK'
        ELSE 'Erro'
    END AS "CONFERENCIA_4",
    VW.CONTAGEM_5,
    CASE
        WHEN VW.CONTAGEM_5 IS NULL THEN NULL 
        WHEN VW.CONTAGEM_5 = VW.QTDESTLOGICA 
             OR VW.CONTAGEM_5 = VW.CONTAGEM_1
                OR VW.CONTAGEM_5 = VW.CONTAGEM_2 
                    OR VW.CONTAGEM_5 = VW.CONTAGEM_3 
                       OR VW.CONTAGEM_5 = VW.CONTAGEM_4 THEN 'OK'
        ELSE 'Erro'
    END AS "CONFERENCIA_5",
    
    VW.QTD_CONTAGEM_ATIVA,
    VW.NR_CONTAGEM_ATIVA,
    VW.ESTOQUE_COMERCIAL,
    VW.ESTOQUECTE,
    ( NVL(VW.QTD_CONTAGEM_ATIVA,0) - NVL(VW.ESTOQUECTE,0)) AS DIVERGENCIA,
    VW.APURACAO_FINAL,
    VW.STATUS
    
FROM VW_WMSIVTCONTAGEM_DCCO VW
INNER JOIN TGFPRO PROD ON PROD.CODPROD = VW.CODPROD;
