CREATE MATERIALIZED VIEW SANKHYA.VW_MAT_FERIASVENCIDAS_DCCO
    (CODEMP, CODFUNC, NOMEFUNC, EMAIL, DTINIAQUI,
     SEQUENCIA, DTFINAQUI, DTPREVISTA, DATALIMITEGOZO, DIASATELIMITE,
     DTSAIDA, FALTPER, NUMDIASFER, ATUALFERGOZ, SITUACAO, SITUATION)
TABLESPACE SANKHYA
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
    INITIAL 160K
    NEXT 160K
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
    PCTINCREASE 0
    BUFFER_POOL DEFAULT
)
NOCACHE
NOLOGGING
NOCOMPRESS
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
WITH PRIMARY KEY
AS
SELECT
    FER.CODEMP,
    FER.CODFUNC,
    FUN.NOMEFUNC,
    FUN.EMAIL,
    FER.DTINIAQUI,
    FER.SEQUENCIA,
    FER.DTFINAQUI,
    FER.DTPREVISTA,
    (TRUNC(FER.DTFINAQUI) + 336) AS DATALIMITEGOZO,
    ((TRUNC(FER.DTFINAQUI) + 336) - TRUNC(SYSDATE)) AS DIASATELIMITE,
    FER.DTSAIDA,
    FER.FALTPER,
    FER.NUMDIASFER,
    FER.ATUALFERGOZ,
    FUN.SITUACAO,
    fc_valor_opcao('TFPFUN', 'SITUACAO', FUN.SITUACAO) AS SITUATION
FROM
    TFPFER FER
INNER JOIN
    TFPFUN FUN ON FUN.CODFUNC = FER.CODFUNC AND FUN.CODEMP = FER.CODEMP
WHERE
    FER.ATUALFERGOZ = 'N'
    AND FER.DTSAIDA IS NULL
    AND FER.DTPREVISTA IS NULL
    AND FUN.SITUACAO IN (1,5)
    AND TRUNC(SYSDATE) - TRUNC(FER.DTFINAQUI) <= 90
    AND TRUNC(SYSDATE) - TRUNC(FER.DTFINAQUI) > 0;
