-- View Materializada que é atualizada todas as madrugadas.
-- Ela gera uma lista dos colaboradores que têm suas férias com vencimento em até 7 dias.
-- Script utilizado em um Cartão inteligente na área de trabalho do Sankhya.

CREATE MATERIALIZED VIEW VW_MAT_RECIBOFERIASAPPES_DCCO
REFRESH COMPLETE ON DEMAND
START WITH TRUNC(SYSDATE) + INTERVAL '14' HOUR
NEXT SYSDATE + INTERVAL '1' DAY + INTERVAL '5' HOUR
AS
SELECT
  SFE.NUSOLICIT,
  SFE.CODEMP,
  FUN.CODUSU,
  SFE.CODFUNC,
  FUN.NOMEFUNC,
  SFE.PREVINICIO AS DTPREVISTA,
  SFE.DIASSOLICITADOS AS NUMDIASFER,
  TRUNC((SFE.PREVINICIO + SFE.DIASSOLICITADOS) - 1) AS DTFIM,
  TRUNC(SFE.PREVINICIO - SYSDATE) AS DIAS,
  TRUNC(SFE.PREVINICIO - 30) AS DTLIMITE,
  fc_valor_opcao('TFPSFE', 'STATUS', SFE.STATUS) AS STATUS,
  FUN.EMAIL,
  SFE.ADIANTADECTERC,
  SFE.ABONOPECUNIARIO,
  SFE.AD_EMAILAVISOFERIAS,
  SFE.AD_EMAILRECIBOFERIAS,
  SFE.AD_EMAILGERENTEAVISO
FROM
  TFPSFE SFE
  INNER JOIN TFPFUN FUN ON FUN.CODEMP = SFE.CODEMP AND FUN.CODFUNC = SFE.CODFUNC
WHERE
  SFE.STATUS = 'A'
  AND FUN.SITUACAO = 1
  AND SFE.PREVINICIO - SYSDATE BETWEEN 1 AND 7;
