CREATE OR REPLACE FUNCTION SANKHYA.IS_NUMBER_DCCO(P_VALUE   VARCHAR2)
RETURN NUMBER
IS
  V_VALOR       NUMBER;
  
  P_NV_VALUE    VARCHAR2(4000) := P_VALUE;
BEGIN
              -- VALIDAR SE É NÚMERO OU NÃO
    IF LENGTH(P_VALUE) = 1 AND P_VALUE = '-' THEN
      P_NV_VALUE := 0;
    ELSE
      P_NV_VALUE := P_VALUE;
    END IF;
    
    BEGIN
      SELECT TO_NUMBER(P_NV_VALUE) INTO V_VALOR
      FROM DUAL;
    EXCEPTION
    WHEN OTHERS THEN
      RETURN NULL;
    END;

    RETURN V_VALOR;

END;

/