SELECT
       upper(T.NOMEFUNC) as NOMEFUNC,
       T.DIA,
       T.MES,
       T.MESDESCR,
       T.CODEMP,
       T.NOMEFANTASIA,
       T.COMEMORAANIVERSARIO,
       T.COMEMORADTFESTIVAS

FROM
(
SELECT

      DISTINCT(FUN.NOMEFUNC),
      TO_NUMBER(TO_CHAR(FUN.DTNASC,'DD')) dia,
      TO_NUMBER(TO_CHAR(FUN.DTNASC,'MM')) mes,
      INITCAP(TO_CHAR(AO.DTNASC,'MONTH')) MESDESCR,
      FUN.CODEMP,
      EMP.NOMEFANTASIA,
      DECODE(NVL(AO.COMEMORANIVER,'S'), 'N','NAO','SIM') AS COMEMORAANIVERSARIO,
      AO.COMEMORADTFESTIVAS

FROM TFPFUN FUN

INNER JOIN TSIEMP EMP ON EMP.CODEMP = FUN.CODEMP
INNER JOIN TSIUSU USU ON USU.CODFUNC = FUN.CODFUNC AND USU.CODEMP = FUN.CODEMP
INNER JOIN AD_TBTIAGENDAONLINE AO ON AO.CODFUNC = FUN.CODFUNC AND AO.CODEMP = FUN.CODEMP

WHERE FUN.SITUACAO NOT IN (0,8)
--AND USU.DTLIMACESSO IS NULL
--AND   AO.ATIVO = 'S'
AND   TO_NUMBER(TO_CHAR(AO.DTNASC,'MM')) = $P{Mes}
AND AO.DTNASC IS NOT NULL


UNION

SELECT
       DISTINCT(AO.NOMECOMPLT) as NOMEFUNC,
       TO_NUMBER(TO_CHAR(AO.DTNASC,'DD')) dia,
       TO_NUMBER(TO_CHAR(AO.DTNASC,'MM')) mes,
       INITCAP(TO_CHAR(AO.DTNASC,'MONTH')) MESDESCR,
       AO.CODEMP,
       EMP.NOMEFANTASIA,
       DECODE(AO.COMEMORANIVER, 'S','SIM','NAO') AS COMEMORAANIVERSARIO,
       AO.COMEMORADTFESTIVAS

FROM AD_TBTIAGENDAONLINE AO

INNER JOIN TSIEMP EMP ON EMP.CODEMP = AO.CODEMP
INNER JOIN TSIUSU USU ON AO.CODUSU = USU.CODUSU

WHERE USU.AD_PJ = 'S'
AND USU.DTLIMACESSO IS NULL
AND AO.DTNASC IS NOT NULL
AND AO.ATIVO = 'S'
AND TO_NUMBER(TO_CHAR(AO.DTNASC,'MM')) = $P{Mes}

) T
ORDER BY T.CODEMP,T.MES,T.DIA,T.NOMEFUNC